name: 'dbsql_dbt_tpch'
version: '1.0.0'
config-version: 2

profile: 'sql_endpoints'

vars:
  benchmark: 10000




model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


dispatch:
 - macro_namespace: dbt_utils
   search_order: ['dbsql_dbt_tpch', 'dbt_utils']
