CREATE OR REPLACE FILE FORMAT database.schema.TXT_FIXED_WIDTH
TYPE = CSV
COMPRESSION = 'AUTO'
FIELD_DELIMITER = NONE
RECORD_DELIMITER = '\n'
SKIP_HEADER = 0
TRIM_SPACE = FALSE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
NULL_IF = ('\\n') ;